package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/Khan/genqlient/graphql"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &ServiceDomainResource{}
var _ resource.ResourceWithImportState = &ServiceDomainResource{}

func NewServiceDomainResource() resource.Resource {
	return &ServiceDomainResource{}
}

type ServiceDomainResource struct {
	client *graphql.Client
}

type ServiceDomainResourceModel struct {
	Id            types.String `tfsdk:"id"`
	Subdomain     types.String `tfsdk:"subdomain"`
	EnvironmentId types.String `tfsdk:"environment_id"`
	ServiceId     types.String `tfsdk:"service_id"`
	ProjectId     types.String `tfsdk:"project_id"`
	Suffix        types.String `tfsdk:"suffix"`
	Domain        types.String `tfsdk:"domain"`
}

func (r *ServiceDomainResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_service_domain"
}

func (r *ServiceDomainResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Railway service domain. Creates a Railway-provided `.up.railway.app` domain for a service. The subdomain is auto-generated by Railway and cannot be customized. For custom subdomains, use `railway_custom_domain` instead.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Identifier of the service domain.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"subdomain": schema.StringAttribute{
				MarkdownDescription: "Subdomain of the service domain. Auto-generated by Railway.",
				Computed:            true,
			},
			"environment_id": schema.StringAttribute{
				MarkdownDescription: "Identifier of the environment the service domain belongs to.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.RegexMatches(uuidRegex(), "must be an id"),
				},
			},
			"service_id": schema.StringAttribute{
				MarkdownDescription: "Identifier of the service the service domain belongs to.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.RegexMatches(uuidRegex(), "must be an id"),
				},
			},
			"project_id": schema.StringAttribute{
				MarkdownDescription: "Identifier of the project the service domain belongs to.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"suffix": schema.StringAttribute{
				MarkdownDescription: "Suffix of the service domain (e.g. `up.railway.app`).",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"domain": schema.StringAttribute{
				MarkdownDescription: "Full domain name (e.g. `my-service-abc1.up.railway.app`).",
				Computed:            true,
			},
		},
	}
}

func (r *ServiceDomainResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*graphql.Client)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *graphql.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *ServiceDomainResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *ServiceDomainResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	input := ServiceDomainCreateInput{
		ServiceId:     data.ServiceId.ValueString(),
		EnvironmentId: data.EnvironmentId.ValueString(),
	}

	response, err := createServiceDomain(ctx, *r.client, input)

	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create service domain, got error: %s", err))
		return
	}

	tflog.Trace(ctx, "created a service domain")

	domain := response.ServiceDomainCreate.ServiceDomain

	// Save state immediately so Terraform tracks this resource.
	// If getService fails below, the resource will be tainted
	// and scheduled for destroy+recreate on the next apply.
	populateServiceDomainModel(data, &domain)
	// ProjectId not yet known — set null so state has no unknowns.
	data.ProjectId = types.StringNull()

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Look up the project ID from the service.
	service, err := getService(ctx, *r.client, domain.ServiceId)

	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read service, got error: %s", err))
		return
	}

	data.ProjectId = types.StringValue(service.Service.ProjectId)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ServiceDomainResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *ServiceDomainResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	serviceDomain, err := findServiceDomainById(ctx, *r.client, data.ProjectId.ValueString(), data.EnvironmentId.ValueString(), data.ServiceId.ValueString(), data.Id.ValueString())

	if err != nil {
		if isNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read service domain, got error: %s", err))
		return
	}

	// Refresh all values from the API per Terraform Plugin Framework best practices.
	populateServiceDomainModel(data, serviceDomain)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ServiceDomainResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// All user-configurable fields have RequiresReplace(), so Update is never called.
	// Railway's public API does not support renaming service domains.
	resp.Diagnostics.AddError("Not Supported", "Service domain updates are not supported by the Railway API. All changes require replacement.")
}

func (r *ServiceDomainResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *ServiceDomainResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	_, err := deleteServiceDomain(ctx, *r.client, data.Id.ValueString())

	if err != nil && !isNotFound(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete service domain, got error: %s", err))
		return
	}

	tflog.Trace(ctx, "deleted a service domain")
}

func (r *ServiceDomainResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")

	if len(parts) != 3 || parts[0] == "" || parts[1] == "" || parts[2] == "" {
		resp.Diagnostics.AddError(
			"Unexpected Import Identifier",
			fmt.Sprintf("Expected import identifier with format: service_id:environment_name:domain. Got: %q", req.ID),
		)

		return
	}

	serviceId := parts[0]
	environmentName := parts[1]
	domainName := parts[2]

	service, err := getService(ctx, *r.client, serviceId)

	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read service, got error: %s", err))
		return
	}

	projectId := service.Service.ProjectId
	environmentIdPtr, err := findEnvironment(ctx, *r.client, projectId, environmentName)

	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read environment, got error: %s", err))
		return
	}

	environmentId := *environmentIdPtr

	// Look up the domain to get its ID, which Read() needs.
	serviceDomain, err := findServiceDomainByName(ctx, *r.client, projectId, environmentId, serviceId, domainName)

	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to find service domain %q, got error: %s", domainName, err))
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), serviceDomain.Id)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("domain"), serviceDomain.Domain)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("service_id"), serviceId)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("environment_id"), environmentId)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("project_id"), projectId)...)
}

// populateServiceDomainModel sets all domain fields from the API response.
func populateServiceDomainModel(data *ServiceDomainResourceModel, domain *ServiceDomain) {
	data.Id = types.StringValue(domain.Id)
	data.EnvironmentId = types.StringValue(domain.EnvironmentId)
	data.ServiceId = types.StringValue(domain.ServiceId)
	data.Suffix = types.StringValue(domain.Suffix)
	data.Domain = types.StringValue(domain.Domain)

	if len(domain.Domain) > len(domain.Suffix)+1 {
		data.Subdomain = types.StringValue(domain.Domain[:len(domain.Domain)-len(domain.Suffix)-1])
	} else {
		data.Subdomain = types.StringValue(domain.Domain)
	}
}

// findServiceDomainById searches for a domain by its ID.
func findServiceDomainById(ctx context.Context, client graphql.Client, projectId string, environmentId string, serviceId string, domainId string) (*ServiceDomain, error) {
	response, err := listServiceDomains(ctx, client, environmentId, serviceId, projectId)
	if err != nil {
		return nil, err
	}

	for _, serviceDomain := range response.Domains.ServiceDomains {
		if serviceDomain.ServiceDomain.Id == domainId {
			return &serviceDomain.ServiceDomain, nil
		}
	}

	return nil, &NotFoundError{ResourceType: "service domain", Id: domainId}
}

// findServiceDomainByName searches for a domain by its full domain name.
// Used by ImportState to resolve the domain ID from a human-readable name.
func findServiceDomainByName(ctx context.Context, client graphql.Client, projectId string, environmentId string, serviceId string, domain string) (*ServiceDomain, error) {
	response, err := listServiceDomains(ctx, client, environmentId, serviceId, projectId)
	if err != nil {
		return nil, err
	}

	for _, serviceDomain := range response.Domains.ServiceDomains {
		if serviceDomain.ServiceDomain.Domain == domain {
			return &serviceDomain.ServiceDomain, nil
		}
	}

	return nil, &NotFoundError{ResourceType: "service domain", Id: domain}
}
